### ISSUE TITLE
Dm istek

### ISSUE THREAD

**Issue by huseyinkarael** [nrucel/instagram-follow-and-like-tools#1]
Merhaba,
Giriş yapan hesapların otomatik takipçilerine belirlediğim url adresini dm olarak atmasını nasıl yapabilirim

**Comment by nrucel** [comment]
Merhaba tüm işlemler bizim ip adreslerimizden yapıldığı için bu işleme izin vermiyoruz maalesef. Bu hafta içinde video, hikaye canlı yayın izlenme, yorum beğeni scripte eklenecek. Not olarak giren kullanıcıların hesabı üzerinden düzeltmelere izin vermiyoruz. Sebebi ise şikayetlerde siber suçların direk bizle irtibata geçmesi.kendiniz sıfırdan yazmak isterseniz github'ta mgp25'in yapmış olduğu kütüphaneyi önerebilirim.30.12.2018, 08:12, "huseyinkarael" <notifications@github.com>:Merhaba,
Giriş yapan hesapların otomatik takipçilerine belirlediğim url adresini dm olarak atmasını nasıl yapabilirim

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- Nurullah ÇELİK (NRUCEL)
